# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_ui.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1329, 851)
        MainWindow.setMinimumSize(QSize(1329, 851))
        MainWindow.setMaximumSize(QSize(1329, 851))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.urlInfo = QLabel(self.centralwidget)
        self.urlInfo.setObjectName(u"urlInfo")
        self.urlInfo.setGeometry(QRect(430, 10, 481, 16))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(11, 40, 1310, 781))
        self.tabWidget.setMaximumSize(QSize(4564665, 781))
        self.aniSearchTab = QWidget()
        self.aniSearchTab.setObjectName(u"aniSearchTab")
        self.aniSearchBox = QLineEdit(self.aniSearchTab)
        self.aniSearchBox.setObjectName(u"aniSearchBox")
        self.aniSearchBox.setGeometry(QRect(340, 31, 821, 31))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aniSearchBox.setFont(font)
        self.aniSearchBtn = QPushButton(self.aniSearchTab)
        self.aniSearchBtn.setObjectName(u"aniSearchBtn")
        self.aniSearchBtn.setGeometry(QRect(1180, 31, 111, 31))
        self.setSiteFrame = QFrame(self.aniSearchTab)
        self.setSiteFrame.setObjectName(u"setSiteFrame")
        self.setSiteFrame.setGeometry(QRect(10, 51, 301, 61))
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.setSiteFrame.setFont(font1)
        self.setSiteFrame.setAutoFillBackground(False)
        self.setSiteFrame.setStyleSheet(u"")
        self.setSiteFrame.setFrameShape(QFrame.Box)
        self.setSiteFrame.setFrameShadow(QFrame.Raised)
        self.setSiteFrame.setLineWidth(1)
        self.setSiteYaAni24rBtn = QRadioButton(self.setSiteFrame)
        self.setSiteBtnGroup = QButtonGroup(MainWindow)
        self.setSiteBtnGroup.setObjectName(u"setSiteBtnGroup")
        self.setSiteBtnGroup.addButton(self.setSiteYaAni24rBtn)
        self.setSiteYaAni24rBtn.setObjectName(u"setSiteYaAni24rBtn")
        self.setSiteYaAni24rBtn.setGeometry(QRect(160, 20, 91, 19))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setBold(True)
        font2.setWeight(75)
        self.setSiteYaAni24rBtn.setFont(font2)
        self.setSiteAni24rBtn = QRadioButton(self.setSiteFrame)
        self.setSiteBtnGroup.addButton(self.setSiteAni24rBtn)
        self.setSiteAni24rBtn.setObjectName(u"setSiteAni24rBtn")
        self.setSiteAni24rBtn.setGeometry(QRect(19, 20, 91, 19))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setWeight(75)
        self.setSiteAni24rBtn.setFont(font3)
        self.setWayFrame = QFrame(self.aniSearchTab)
        self.setWayFrame.setObjectName(u"setWayFrame")
        self.setWayFrame.setGeometry(QRect(10, 156, 301, 171))
        self.setWayFrame.setFrameShape(QFrame.Box)
        self.searchKeyWordRBtn = QRadioButton(self.setWayFrame)
        self.setSearchWayBtnGroup = QButtonGroup(MainWindow)
        self.setSearchWayBtnGroup.setObjectName(u"setSearchWayBtnGroup")
        self.setSearchWayBtnGroup.addButton(self.searchKeyWordRBtn)
        self.searchKeyWordRBtn.setObjectName(u"searchKeyWordRBtn")
        self.searchKeyWordRBtn.setGeometry(QRect(160, 20, 81, 21))
        self.searchKeyWordRBtn.setFont(font)
        self.completeRBtn = QRadioButton(self.setWayFrame)
        self.setSearchWayBtnGroup.addButton(self.completeRBtn)
        self.completeRBtn.setObjectName(u"completeRBtn")
        self.completeRBtn.setGeometry(QRect(19, 20, 61, 19))
        self.completeRBtn.setFont(font3)
        self.quarterTop20rBtn = QRadioButton(self.setWayFrame)
        self.setSearchWayBtnGroup.addButton(self.quarterTop20rBtn)
        self.quarterTop20rBtn.setObjectName(u"quarterTop20rBtn")
        self.quarterTop20rBtn.setGeometry(QRect(19, 100, 121, 19))
        self.quarterTop20rBtn.setFont(font)
        self.newTop20rBtn = QRadioButton(self.setWayFrame)
        self.setSearchWayBtnGroup.addButton(self.newTop20rBtn)
        self.newTop20rBtn.setObjectName(u"newTop20rBtn")
        self.newTop20rBtn.setGeometry(QRect(19, 60, 121, 19))
        self.newTop20rBtn.setFont(font)
        self.yearTop20rBtn = QRadioButton(self.setWayFrame)
        self.setSearchWayBtnGroup.addButton(self.yearTop20rBtn)
        self.yearTop20rBtn.setObjectName(u"yearTop20rBtn")
        self.yearTop20rBtn.setGeometry(QRect(160, 100, 121, 19))
        self.yearTop20rBtn.setFont(font)
        self.genreTop20rBtn = QRadioButton(self.setWayFrame)
        self.setSearchWayBtnGroup.addButton(self.genreTop20rBtn)
        self.genreTop20rBtn.setObjectName(u"genreTop20rBtn")
        self.genreTop20rBtn.setGeometry(QRect(160, 60, 121, 19))
        self.genreTop20rBtn.setFont(font)
        self.tasteRBtn = QRadioButton(self.setWayFrame)
        self.setSearchWayBtnGroup.addButton(self.tasteRBtn)
        self.tasteRBtn.setObjectName(u"tasteRBtn")
        self.tasteRBtn.setGeometry(QRect(19, 140, 108, 19))
        self.tasteRBtn.setFont(font3)
        self.setTagFrame = QFrame(self.aniSearchTab)
        self.setTagFrame.setObjectName(u"setTagFrame")
        self.setTagFrame.setGeometry(QRect(10, 372, 301, 371))
        self.setTagFrame.setFrameShape(QFrame.Box)
        self.clothesComboBox = QComboBox(self.setTagFrame)
        self.clothesComboBox.setObjectName(u"clothesComboBox")
        self.clothesComboBox.setGeometry(QRect(118, 219, 161, 21))
        self.quarterLabel = QLabel(self.setTagFrame)
        self.quarterLabel.setObjectName(u"quarterLabel")
        self.quarterLabel.setGeometry(QRect(17, 140, 41, 21))
        self.clothesLabel = QLabel(self.setTagFrame)
        self.clothesLabel.setObjectName(u"clothesLabel")
        self.clothesLabel.setGeometry(QRect(17, 219, 91, 21))
        self.playWayLabel = QLabel(self.setTagFrame)
        self.playWayLabel.setObjectName(u"playWayLabel")
        self.playWayLabel.setGeometry(QRect(17, 179, 91, 21))
        self.playWayComboBox = QComboBox(self.setTagFrame)
        self.playWayComboBox.setObjectName(u"playWayComboBox")
        self.playWayComboBox.setGeometry(QRect(118, 179, 161, 21))
        self.hairColorLabel = QLabel(self.setTagFrame)
        self.hairColorLabel.setObjectName(u"hairColorLabel")
        self.hairColorLabel.setGeometry(QRect(17, 299, 91, 21))
        self.producerComboBox = QComboBox(self.setTagFrame)
        self.producerComboBox.setObjectName(u"producerComboBox")
        self.producerComboBox.setGeometry(QRect(118, 59, 161, 21))
        self.hairStyleLabel = QLabel(self.setTagFrame)
        self.hairStyleLabel.setObjectName(u"hairStyleLabel")
        self.hairStyleLabel.setGeometry(QRect(17, 259, 91, 21))
        self.hairStyleComboBox = QComboBox(self.setTagFrame)
        self.hairStyleComboBox.setObjectName(u"hairStyleComboBox")
        self.hairStyleComboBox.setGeometry(QRect(118, 259, 161, 21))
        self.quarterComboBox = QComboBox(self.setTagFrame)
        self.quarterComboBox.setObjectName(u"quarterComboBox")
        self.quarterComboBox.setGeometry(QRect(118, 139, 161, 21))
        self.hairColorComboBox = QComboBox(self.setTagFrame)
        self.hairColorComboBox.setObjectName(u"hairColorComboBox")
        self.hairColorComboBox.setGeometry(QRect(118, 299, 161, 21))
        self.producerLabel = QLabel(self.setTagFrame)
        self.producerLabel.setObjectName(u"producerLabel")
        self.producerLabel.setGeometry(QRect(17, 60, 61, 20))
        self.yearLabel = QLabel(self.setTagFrame)
        self.yearLabel.setObjectName(u"yearLabel")
        self.yearLabel.setGeometry(QRect(17, 100, 41, 21))
        self.gerneComboBox = QComboBox(self.setTagFrame)
        self.gerneComboBox.setObjectName(u"gerneComboBox")
        self.gerneComboBox.setGeometry(QRect(118, 19, 161, 21))
        self.yearComboBox = QComboBox(self.setTagFrame)
        self.yearComboBox.setObjectName(u"yearComboBox")
        self.yearComboBox.setGeometry(QRect(118, 99, 161, 21))
        self.genreLabel = QLabel(self.setTagFrame)
        self.genreLabel.setObjectName(u"genreLabel")
        self.genreLabel.setGeometry(QRect(17, 20, 41, 21))
        self.typeLabel = QLabel(self.setTagFrame)
        self.typeLabel.setObjectName(u"typeLabel")
        self.typeLabel.setGeometry(QRect(17, 339, 91, 21))
        self.typeComboBox = QComboBox(self.setTagFrame)
        self.typeComboBox.setObjectName(u"typeComboBox")
        self.typeComboBox.setGeometry(QRect(118, 339, 161, 21))
        self.aniSiteCheckLabel = QLabel(self.aniSearchTab)
        self.aniSiteCheckLabel.setObjectName(u"aniSiteCheckLabel")
        self.aniSiteCheckLabel.setGeometry(QRect(10, 31, 131, 16))
        font4 = QFont()
        font4.setBold(True)
        font4.setWeight(75)
        self.aniSiteCheckLabel.setFont(font4)
        self.aniSearchWayLabel = QLabel(self.aniSearchTab)
        self.aniSearchWayLabel.setObjectName(u"aniSearchWayLabel")
        self.aniSearchWayLabel.setGeometry(QRect(10, 136, 111, 16))
        self.aniSearchWayLabel.setFont(font4)
        self.aniSelectTagLabel = QLabel(self.aniSearchTab)
        self.aniSelectTagLabel.setObjectName(u"aniSelectTagLabel")
        self.aniSelectTagLabel.setGeometry(QRect(10, 354, 111, 16))
        font5 = QFont()
        font5.setBold(True)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setWeight(75)
        font5.setStrikeOut(False)
        font5.setKerning(True)
        self.aniSelectTagLabel.setFont(font5)
        self.searchTable = QTableWidget(self.aniSearchTab)
        self.searchTable.setObjectName(u"searchTable")
        self.searchTable.setGeometry(QRect(340, 83, 951, 661))
        self.tabWidget.addTab(self.aniSearchTab, "")
        self.aniDownloadTab = QWidget()
        self.aniDownloadTab.setObjectName(u"aniDownloadTab")
        self.aniEpiLinkBox = QLineEdit(self.aniDownloadTab)
        self.aniEpiLinkBox.setObjectName(u"aniEpiLinkBox")
        self.aniEpiLinkBox.setGeometry(QRect(10, 20, 1151, 31))
        self.aniEpiLinkBox.setFont(font)
        self.aniEpiSearchBtn = QPushButton(self.aniDownloadTab)
        self.aniEpiSearchBtn.setObjectName(u"aniEpiSearchBtn")
        self.aniEpiSearchBtn.setGeometry(QRect(1170, 20, 121, 31))
        self.aniEpiList = QListWidget(self.aniDownloadTab)
        self.aniEpiList.setObjectName(u"aniEpiList")
        self.aniEpiList.setGeometry(QRect(10, 100, 421, 641))
        self.aniEpiListLabel = QLabel(self.aniDownloadTab)
        self.aniEpiListLabel.setObjectName(u"aniEpiListLabel")
        self.aniEpiListLabel.setGeometry(QRect(10, 80, 121, 16))
        self.aniEpiListLabel.setFont(font4)
        self.checkAllBox = QCheckBox(self.aniDownloadTab)
        self.checkAllBox.setObjectName(u"checkAllBox")
        self.checkAllBox.setGeometry(QRect(343, 80, 91, 19))
        self.aniDownloadLog = QListWidget(self.aniDownloadTab)
        self.aniDownloadLog.setObjectName(u"aniDownloadLog")
        self.aniDownloadLog.setGeometry(QRect(570, 100, 721, 601))
        self.downloadProgressBar = QProgressBar(self.aniDownloadTab)
        self.downloadProgressBar.setObjectName(u"downloadProgressBar")
        self.downloadProgressBar.setGeometry(QRect(570, 717, 731, 23))
        self.downloadProgressBar.setValue(0)
        self.aniDownloadLogLabel = QLabel(self.aniDownloadTab)
        self.aniDownloadLogLabel.setObjectName(u"aniDownloadLogLabel")
        self.aniDownloadLogLabel.setGeometry(QRect(570, 80, 141, 16))
        self.aniDownloadLogLabel.setFont(font4)
        self.aniDownloadBtn = QPushButton(self.aniDownloadTab)
        self.aniDownloadBtn.setObjectName(u"aniDownloadBtn")
        self.aniDownloadBtn.setGeometry(QRect(440, 390, 121, 31))
        self.tabWidget.addTab(self.aniDownloadTab, "")
        self.settingsTab = QWidget()
        self.settingsTab.setObjectName(u"settingsTab")
        self.settingsFrame = QFrame(self.settingsTab)
        self.settingsFrame.setObjectName(u"settingsFrame")
        self.settingsFrame.setGeometry(QRect(10, 60, 431, 681))
        self.settingsFrame.setFrameShape(QFrame.Box)
        self.settingsFrame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.settingsFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 0, 221, 101))
        self.loadNewInfo = QPushButton(self.settingsFrame)
        self.loadNewInfo.setObjectName(u"loadNewInfo")
        self.loadNewInfo.setGeometry(QRect(260, 40, 141, 28))
        self.helpFrame = QFrame(self.settingsTab)
        self.helpFrame.setObjectName(u"helpFrame")
        self.helpFrame.setGeometry(QRect(480, 60, 371, 681))
        self.helpFrame.setFrameShape(QFrame.Box)
        self.helpFrame.setFrameShadow(QFrame.Raised)
        self.help1Label = QLabel(self.helpFrame)
        self.help1Label.setObjectName(u"help1Label")
        self.help1Label.setGeometry(QRect(20, 30, 301, 91))
        self.help1Label.setFrameShape(QFrame.StyledPanel)
        self.help1Label.setTextFormat(Qt.AutoText)
        self.help1Label.setWordWrap(False)
        self.settingsLabel = QLabel(self.settingsTab)
        self.settingsLabel.setObjectName(u"settingsLabel")
        self.settingsLabel.setGeometry(QRect(14, 30, 41, 31))
        font6 = QFont()
        font6.setPointSize(12)
        font6.setBold(True)
        font6.setWeight(75)
        self.settingsLabel.setFont(font6)
        self.helpLabel = QLabel(self.settingsTab)
        self.helpLabel.setObjectName(u"helpLabel")
        self.helpLabel.setGeometry(QRect(480, 30, 71, 31))
        self.helpLabel.setFont(font6)
        self.developFrame = QFrame(self.settingsTab)
        self.developFrame.setObjectName(u"developFrame")
        self.developFrame.setGeometry(QRect(890, 58, 391, 681))
        self.developFrame.setFrameShape(QFrame.Box)
        self.developFrame.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.developFrame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 40, 161, 41))
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.developFrame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 90, 281, 41))
        self.label_8.setFont(font4)
        self.label_9 = QLabel(self.developFrame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 140, 331, 41))
        self.label_9.setFont(font4)
        self.label_10 = QLabel(self.developFrame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 190, 331, 41))
        self.label_10.setFont(font4)
        self.developLabel = QLabel(self.settingsTab)
        self.developLabel.setObjectName(u"developLabel")
        self.developLabel.setGeometry(QRect(892, 30, 121, 31))
        self.developLabel.setFont(font6)
        self.tabWidget.addTab(self.settingsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.urlInfo.setText(QCoreApplication.translate("MainWindow", u"\uc560\ub2c824: https://ani24do.com                \uc57c\uc560\ub2c824: https://yaani24.net", None))
        self.aniSearchBtn.setText(QCoreApplication.translate("MainWindow", u"\uc560\ub2c8 \uac80\uc0c9", None))
        self.setSiteYaAni24rBtn.setText(QCoreApplication.translate("MainWindow", u"\uc57c\uc560\ub2c824", None))
        self.setSiteAni24rBtn.setText(QCoreApplication.translate("MainWindow", u"\uc560\ub2c824", None))
        self.searchKeyWordRBtn.setText(QCoreApplication.translate("MainWindow", u"\ud0a4\uc6cc\ub4dc", None))
        self.completeRBtn.setText(QCoreApplication.translate("MainWindow", u"\uc644\uacb0", None))
        self.quarterTop20rBtn.setText(QCoreApplication.translate("MainWindow", u"\ubd84\uae30 Top20", None))
        self.newTop20rBtn.setText(QCoreApplication.translate("MainWindow", u"\uc2e0\uc791 Top20", None))
        self.yearTop20rBtn.setText(QCoreApplication.translate("MainWindow", u"\uc62c\ud574 Top20", None))
        self.genreTop20rBtn.setText(QCoreApplication.translate("MainWindow", u"\uc7a5\ub974 Top20", None))
        self.tasteRBtn.setText(QCoreApplication.translate("MainWindow", u"\ucde8\ud5a5 \ub9de\ucda4", None))
        self.quarterLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\ubd84\uae30</span></p></body></html>", None))
        self.clothesLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\uc637</span></p></body></html>", None))
        self.playWayLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\ud50c\ub808\uc774\ubc29\uc2dd</span></p></body></html>", None))
        self.hairColorLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\uba38\ub9ac\uc0c9</span></p></body></html>", None))
        self.hairStyleLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\uba38\ub9ac\uc2a4\ud0c0\uc77c</span></p></body></html>", None))
        self.producerLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\uc81c\uc791\uc0ac</span></p></body></html>", None))
        self.yearLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\uc5f0\ub3c4</span></p></body></html>", None))
        self.genreLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\uc7a5\ub974</span></p></body></html>", None))
        self.typeLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">\ud0c0\uc785</span></p></body></html>", None))
        self.aniSiteCheckLabel.setText(QCoreApplication.translate("MainWindow", u"\uac80\uc0c9 \uc0ac\uc774\ud2b8 \uc120\ud0dd", None))
        self.aniSearchWayLabel.setText(QCoreApplication.translate("MainWindow", u"\uac80\uc0c9 \ubc29\ubc95 \uc120\ud0dd", None))
        self.aniSelectTagLabel.setText(QCoreApplication.translate("MainWindow", u"\uac80\uc0c9 \ud0dc\uadf8 \uc120\ud0dd", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aniSearchTab), QCoreApplication.translate("MainWindow", u"\uc560\ub2c8 \uac80\uc0c9", None))
        self.aniEpiSearchBtn.setText(QCoreApplication.translate("MainWindow", u"\uc560\ub2c8 \ud69f\ucc28 \uac80\uc0c9", None))
        self.aniEpiListLabel.setText(QCoreApplication.translate("MainWindow", u"\uc560\ub2c8 \ud69f\ucc28 \ub9ac\uc2a4\ud2b8", None))
        self.checkAllBox.setText(QCoreApplication.translate("MainWindow", u"\uc804\uccb4 \uc120\ud0dd", None))
        self.aniDownloadLogLabel.setText(QCoreApplication.translate("MainWindow", u"\uc560\ub2c8 \ub2e4\uc6b4\ub85c\ub4dc \ub85c\uadf8", None))
        self.aniDownloadBtn.setText(QCoreApplication.translate("MainWindow", u"\uc560\ub2c8 \ub2e4\uc6b4\ub85c\ub4dc", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aniDownloadTab), QCoreApplication.translate("MainWindow", u"\uc560\ub2c8 \ub2e4\uc6b4\ub85c\ub4dc", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Ani24 Info File\uc744 \uac00\uc838\uc635\ub2c8\ub2e4.\n"
"\ucc98\uc74c\uc774\ub098 \uc5c5\ub370\uc774\ud2b8 \ud558\uace0 \uc2f6\uc744\ub54c \n"
"\ubd88\ub7ec\uc624\uc2dc\uba74 \ub429\ub2c8\ub2e4.", None))
        self.loadNewInfo.setText(QCoreApplication.translate("MainWindow", u"\uc0c8 \uc815\ubcf4 \ubd88\ub7ec\uc624\uae30", None))
        self.help1Label.setText(QCoreApplication.translate("MainWindow", u"[\uac80\uc0c9 \ubc29\ubc95 \uc124\uba85]\n"
"\ud0a4\uc6cc\ub4dc\ub294 \uc606 \uac80\uc0c9\ubc15\uc2a4\uc5d0 \uac80\uc0c9\uc5b4\ub97c\n"
"\uc785\ub825\ud558\uba74 \ub429\ub2c8\ub2e4.\n"
"\uadf8\ub9ac\uace0 \uac80\uc0c9\ubc84\ud2bc\uc740 \uac80\uc0c9\ubc15\uc2a4 \uc606\n"
"[\uc560\ub2c8 \uac80\uc0c9] \ubc84\ud2bc\uc73c\ub85c \ud1b5\uc77c\ub418\uc5b4\uc788\uc2b5\ub2c8\ub2e4.", None))
        self.settingsLabel.setText(QCoreApplication.translate("MainWindow", u"\uc124\uc815", None))
        self.helpLabel.setText(QCoreApplication.translate("MainWindow", u"\ub3c4\uc6c0\ub9d0", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\uc81c\uc791\uc790: \uae40\uacbd\ubbfckdr", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Github: https://github.com/kdrkdrkdr", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Blog: https://blog.naver.com/powerapollon", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"E-Mail: kdrhacker1234@gmail.com", None))
        self.developLabel.setText(QCoreApplication.translate("MainWindow", u"\uac1c\ubc1c\uc790 \uc815\ubcf4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), QCoreApplication.translate("MainWindow", u"\uc124\uc815 \ubc0f \ub3c4\uc6c0\ub9d0", None))
    # retranslateUi

if __name__ == "__main__": 
    import sys 
    app = QApplication(sys.argv) 
    form = QMainWindow() 
    ui = Ui_MainWindow() 
    ui.setupUi(form) 
    form.show() 
    sys.exit(app.exec_()) 
